apiVersion: v1
kind: Service
metadata:
  name: nagastra-service
spec:
  selector:
    app: nagastra-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

  type: NodePort